[package]
edition = "2024"
name    = "esp32-c6-nostd"
version = "0.1.0"

[features]
default = []
experimental = ["esp-idf-svc/experimental"]


[dependencies]
# Basic Access
anyhow = "1"
esp-idf-svc = { version = "0.51" } #, features = ["binstart"] }
esp-idf-hal = { version = "0.45.2", features = [
  "std",
#  "binstart",
] }
# RTT Logging
log = { version = "0.4.27" }

# issue with defmt in rtt_target?
#defmt = "1.0.1"
rtt-target = { version = "0.6.1", features = ["log"] }
#rtt-target = { version = "0.6.1" }

critical-section = { version = "1.2.0", features = ["std"], default-features = false }


#smart-leds = "0.4.0"
#ws2812-spi = {version = "0.5.1",  features = ["mosi_idle_high"]}


[build-dependencies]
embuild = "0.33"


[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[profile.release]
opt-level = "s"
