# Read in the env settings
extend = "./.cargo/env-settings.toml"

[tasks.format]
description = "reformat the rust code using rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.run]
description = "run the app with the env variables set"
command = "cargo"
args = ["run"]
