# Read in the env settings
extend = "../.cargo/env-settings.toml"

[tasks.pyenv]
description = "setup the python virtual environment"
command = "tox"
cwd = "pyvirtenv"
args = ["-c", "tox.ini"]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/../build/pyenv/pyvenv.cfg"] }

[tasks.cmake]
description = "generate the build files using cmake"
cwd = "build"
command = "cmake"
args = ["..", "-G", "Ninja"]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/../build/CMakeCache.txt"] }
dependencies = ["pyenv"]

[tasks.build]
description = "runs ninja to build the project"
cwd = "build"
command = "ninja"
args = []
dependencies = ["cmake"]

[tasks.menuconfig]
description = "select which options for the idf are required"
cwd = "build"
command = "ninja"
args = ["menuconfig"]
dependencies = ["cmake"]
