# Read in the env settings
extend = "./env-settings.toml"

[tasks.pyenv-setup]
description = "setup the python virtual environment"
command = "tox"
cwd = "pyvirtenv"
args = ["-c", "tox.ini"]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/../build/pyenv/pyvenv.cfg"] }

[tasks.cmake]
description = "generate the build files using cmake"
cwd = "build"
command = "cmake"
args = ["..", "-G", "Ninja"]
dependencies = ["pyenv-setup"]

[tasks.build]
description = "runs ninja to build the project"
cwd = "build"
command = "ninja"
args = []
dependencies = ["cmake"]
