# Cargo Make Task runner
# See "cargo make list"

extend = [
  # Read in the settings
  { path = "./blinky-esp32/.cargo/make-env.toml" },
  # Build tools
  { path = "./make/make/Cargo-Make-build.toml" },
  # Flash tools
  { path = "./make/make/Cargo-Make-esptool.toml" },  
]

[env]
CARGO_MAKE_WORKING_DIRECTORY = "./blinky-esp32"
