# Cargo Make Task runner
# Run via "cargo make build"

extend = [
  # Read in the settings
  { path = "./.cargo/env-settings.toml" },
  # Build tools
  { path = "./build/make/Cargo-Make-build.toml" },
  # Flash tools
  { path = "./build/make/Cargo-Make-esptool.toml" },  
]
