# Read in the env settings
extend = ".cargo/env-settings.toml"

[tasks.install-rust-src]
description = "install rust-src via rustup component add"
install_crate = { rustup_component_name = "rust-src" }

[tasks.bindgen]
description = "runs bindgen to generate the bindings, also runs rustfmt at the same time"
command = "python"
args = ["build-bindgen.py"]

[tasks.build]
description = "build the source in debug mode - ESP32"
command = "cargo"
dependencies = [ "install-rust-src" ]
args = ["xbuild", "${@}"]
category = "ESP32-Build"

[tasks.build-release]
description = "build the source in release mode - ESP32"
command = "cargo"
dependencies = [ "install-rust-src" ]
args = ["xbuild", "--release", "${@}"]
category = "ESP32-Build"
