# Read in the env settings
extend = "../.cargo/env-settings.toml"

[tasks.bindgen]
description = "runs bindgen to generate the bindings"
command = "python"
args = ["build-bindgen.py"]

[tasks.format]
description = "reformat the rust code using rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files", "src/bindings.rs"]
