# Read in the settings
extend = "./.cargo/env-settings.toml"

[tasks.install-rust-src]
description = "install rust-src via rustup component add"
install_crate = { rustup_component_name = "rust-src" }

[tasks.format]
description = "reformat the rust code using rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
description = "build the source in debug mode - ESP32"
command = "cargo"
dependencies = [ "install-rust-src" ]
args = ["xbuild", "${@}"]
category = "ESP32-Build"

[tasks.build-release]
description = "build the source in release mode - ESP32"
command = "cargo"
dependencies = [ "install-rust-src" ]
args = ["xbuild", "--release", "${@}"]
category = "ESP32-Build"
