[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["core", "alloc"]

[target.xtensa-esp32-espidf]
runner = "xtensa-esp32-elf-gdb -q -x openocd.gdb"
rustflags = [
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",
]
