# ESP32 Flash Util Tasks

[tasks.flashid]
description = "Get the flashid / details from the esp32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "flash_id", "${@}"]
category = "Common"

[tasks.chipid]
description = "Get the chipid / details from the esp32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "chip_id", "${@}"]
category = "Common"

[tasks.flashstatus]
description = "Get the flash status / details from the esp32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "read_flash_status", "${@}"]
category = "Common"

[tasks.readmac]
description = "Read the mac address of the board"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "read_mac", "${@}"]
category = "Common"

[tasks.eraseflash]
description = "Erase the flash on the ESP32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "erase_flash", "${@}"]
category = "Common"

[tasks.imageinfo]
description = "Show the image info"
condition = { files_exist = [ "${BUILD_BIN_FILE}" ] }
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "image_info", "${BUILD_BIN_FILE}", "${@}"]
category = "Common"

[tasks.elf2image]
description = "Generate a flashable binary from the elf file"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "elf2image", "${BUILD_ELF_FILE}", "${@}"]
dependencies = ["build"]
category = "Common"

[tasks.run]
description = "Trigger running of the flash"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "run", "${@}"]
category = "Common"
