[env]
ESP32_BOOTLOADER = "../../bootloader/esp32-bootloader.bin"
ESP32_PARTBIN = "../../bootloader/partitions.bin"
ESP32_FLASHMODE = "dio"
ESP32_FLASHFREQ = "40m"
ESP32_FLASHSIZE = "detect"

[tasks.flashid]
description = "Get the flashid / details from the esp32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "flash_id", "${@}"]
category = "Common"

[tasks.eraseflash]
description = "Erase the flash on the ESP32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "erase_flash", "${@}"]
category = "Common"

[tasks.imageinfo]
description = "Show the image info"
condition = { files_exist = [ "${BUILD_BIN_FILE}" ] }
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "image_info", "${BUILD_BIN_FILE}", "${@}"]
category = "Common"

[tasks.elf2image]
description = "Generate a flashable binary from the elf file"
command = "python"
args = ["-m", "esptool", "--chip", "esp32", "elf2image", "${BUILD_ELF_FILE}", "${@}"]
dependencies = ["build"]
category = "Common"

[tasks.flash]
description = "Upload / Flash the source to the esp32"
command = "python"
args = ["-m", "esptool", "--chip", "esp32",
"-p", "${ESP32_FLASH_SERIAL}",
"--baud", "${ESP32_FLASH_SERIAL_BAUD}",
"--before", "default_reset", "--after", "hard_reset", "write_flash",
"--flash_mode", "${ESP32_FLASHMODE}",
"--flash_freq", "${ESP32_FLASHFREQ}",
"--flash_size", "${ESP32_FLASHSIZE}",
"0x1000", "${ESP32_BOOTLOADER}",
"0x8000", "${ESP32_PARTBIN}",
"0x10000", "${BUILD_BIN_FILE}",
"${@}"]
dependencies = ["elf2image"]
category = "Common"
