#
# Cargo Configuration for a microbit 1.3
# https://github.com/nrf-rs/microbit

[build]
target = "thumbv6m-none-eabi"          # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"        # Cortex-M3
# target = "thumbv7em-none-eabi"       # Cortex-M4 and Cortex-M7 (no FPU)
# target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
# target = "thumbv8m.base-none-eabi"   # Cortex-M23
# target = "thumbv8m.main-none-eabi"   # Cortex-M33 (no FPU)
# target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)


[env]
# Enable printing of defmt debug, info and warning messages by default
DEFMT_LOG="debug"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']

# Runner for probe-rs
runner = 'probe-rs run --chip nRF51822_xxAA --protocol swd'


# Linker Flags
#
# linker=flip-link
# adds zero-cost stack overflow protection to your embedded programs
# https://github.com/knurling-rs/flip-link
#
# --nmagic
# Turns off page alignment of sections (which saves flash space)
# 
# -Tlink.x 
# Tells the linker to use link.x as a linker script. This is usually provided by the cortex-m-rt crate
# and by default the version in that crate will include a file called `memory.x` which describes
# the particular memory layout for your specific chip. 
#
# -Tdefmt.x
# Also tells the linker to use `defmt.x` as a secondary linker script. This is required to make defmt_rtt work.
#
# target-cpu=xxxx
# Specify the specific CPU in use
# List available CPU's with `rustc --target=thumbv6m-none-eabi --print=target-cpus`
#
# -Tstlog.x
# stlog - https://japaric.github.io/stlog/stlog/

# For micro:bit v1.x
[target.thumbv6m-none-eabi]
rustflags = [
  "-C", "linker=flip-link",
#  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "target-cpu=cortex-m0",
  # "-C", "link-arg=-Tstlog.x",
]
