
# Common to all profiles
[env]
# Show debugging info on error of build
RUST_BACKTRACE = 1
# Use the custom esp toolchain
RUSTUP_TOOLCHAIN="esp"

# Default Profile
[env.development]
BUILD_OUT_DIR = "./${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/debug"
BUILD_ELF_FILE = "${BUILD_OUT_DIR}/${CARGO_MAKE_PROJECT_NAME}"
BUILD_BIN_FILE = "${BUILD_ELF_FILE}.bin"

# Production / Release Profile
[env.production]
BUILD_OUT_DIR = "./${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/release"
BUILD_ELF_FILE = "${BUILD_OUT_DIR}/${CARGO_MAKE_PROJECT_NAME}"
BUILD_BIN_FILE = "${BUILD_ELF_FILE}.bin"


[tasks.build]
description = "build the source - development"
#run_task = [
#    { name = "test1", condition = { platforms = ["windows", "linux"], channels = ["beta", "stable"] } },
#    { name = "test2", condition = { platforms = ["mac"], rust_version = { min = "1.20.0", max = "1.30.0" } } },
#    { name = "test3", condition_script = [ "somecommand" ] },
#    { name = "test-default" }
#]



dependencies = ["build-development", "build-production"]
category = "ESP32"

# TODO
[tasks.build-prod]
description = "build the source - production"
#env = { PROFILE_ENV_KEY = "production" }
#run_task = { name = "build-production", fork = true }
#command = "cargo"
#args = ["make", "--disable-check-for-updates", "--no-on-error", "--loglevel=info",
#"--profile=production", "--allow-private", "--skip-init-end-tasks", "--makefile", "D:\\SourceCode\\Private\\Hecatron\\Embedded.Rust.Examples\\src\\ESP32\\blinky\\Makefile.toml",  "build-production"]
#args = ["make", "build-production"]
#category = "ESP32"



[tasks.build-development]
description = "build the source - development"
condition = { profiles = [ "development" ] }
command = "cargo"
args = ["build"]

[tasks.build-production]
description = "build the source - production"
#condition = { profiles = [ "production" ] }
command = "cargo"
args = ["build", "--release"]


# Todo testing
[tasks.test123]
env = { PROFILE_ENV_KEY = "production" }
run_task = { name = "build-production", fork = true }

#command = "echo"
#args = ["${PROFILE_ENV_KEY}"]
#command = "cargo"
#args = [ "make", "--verbose", "build-production" ]


# "@@split(CARGO_ARGS, )"
# "@@remove-empty(VERBOSE_FLAGS)",
# https://github.com/sagiegurari/cargo-make/discussions/517


# TODO production profile ${@}
#[tasks.build]
#description = "build the source"
#command = "cargo"
#args = ["build", "${BUILD_FLAGS} ${@}"]
#category = "ESP32"

# TODO alias?

#command = "cargo"
#args = ["build", "--release", "${@}"]

#category = "ESP32"




# Reformat Code

[tasks.format]
description = "reformat the rust code using rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]


# List Available Commands

[tasks.list]
command = "rust-script"
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}"
args = ["./usage.ers"]

[tasks.usage]
alias = "list"

[tasks.default]
alias = "list"
