# Read in the env settings
extend = "../.cargo/env-settings.toml"

[tasks.pyenv]
description = "setup the python virtual environment"
command = "tox"
cwd = "pyvirtenv"
args = ["-c", "tox.ini"]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/pyenv/pyvenv.cfg"] }

[tasks.idf]
description = "Run idf.py"
command = "${CARGO_MAKE_WORKING_DIRECTORY}/pyvirtenv/pyenv/Scripts/python.exe"
args = ["${IDF_PATH}/tools/idf.py", "${@}"]
dependencies = ["pyenv"]

[tasks.cmake]
description = "generate the build files using cmake, note idf.py will do this automatically"
cwd = "build"
command = "cmake"
args = ["..", "-G", "Ninja"]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/../build/CMakeCache.txt"] }
dependencies = ["pyenv"]
