[package]
name = "pro-s3-std"
version = "0.1.0"
authors = ["grbd <hecatrons.workshop@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "pro-s3-std"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
# ESP32 std support
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
esp-idf-hal ={ version = "0.45" }

# Used for debug logging
defmt = { version = "0.3" }
rtt-target = { version = "0.6", features = ["defmt"] }
log = "0.4"

# Used for WS2812 LED's
ws2812-spi = { version = "0.5", features = ["mosi_idle_high", "std"]}
#smart-leds-trait = "0.3"
smart-leds = "0.4.0"

[build-dependencies]
embuild = "0.33"
