[package]
name = "simulator1"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.6.0"
rand = { version = "0.8.4", default-features = false, features = [ "small_rng" ] }
